import { useEffect, useMemo, useState } from "react";
import { AnalyticsPanel } from "./components/AnalyticsPanel";
import { MacroBar } from "./components/MacroBar";
import { MealRow } from "./components/MealRow";
import { NewMealDrawer } from "./components/NewMealDrawer";
import { agruparPorDia, fechaLocalDia, formatoDia } from "./lib/date";
import { crearComida, eliminarComida, obtenerComidas } from "./services/comidas";
import "./App.css";

export default function DiarioComidas() {
  const [comidas, setComidas] = useState([]); const [cargando, setCargando] = useState(true); const [error, setError] = useState(null); const [vista, setVista] = useState("diario"); const [panelAbierto, setPanelAbierto] = useState(false); const [textoJson, setTextoJson] = useState(""); const [mensaje, setMensaje] = useState(null); const [guardando, setGuardando] = useState(false); const [expandido, setExpandido] = useState(null); const [confirmandoId, setConfirmandoId] = useState(null);
  async function cargarComidas() { setCargando(true); setError(null); try { setComidas(await obtenerComidas()); } catch (error) { setError(error.message); } finally { setCargando(false); } }
  useEffect(() => { cargarComidas(); }, []);
  async function guardarRegistro() { setGuardando(true); setMensaje(null); try { const registro = JSON.parse(textoJson); await crearComida(registro); setMensaje({ tipo: "ok", texto: `Guardado: ${registro.comida_nombre}` }); setTextoJson(""); setPanelAbierto(false); cargarComidas(); } catch (error) { setMensaje({ tipo: "error", texto: error.message.includes("JSON") ? "El texto no es un JSON válido" : error.message }); } finally { setGuardando(false); } }
  async function borrarComida(id) { try { await eliminarComida(id); setComidas((actuales) => actuales.filter((comida) => comida.id !== id)); setConfirmandoId(null); } catch (error) { setError(error.message); } }
  const totalesHoy = useMemo(() => comidas.filter((comida) => fechaLocalDia(comida.fecha) === fechaLocalDia(new Date())).reduce((total, comida) => ({ calorias: total.calorias + Number(comida.calorias_totales || 0), proteinas: total.proteinas + Number(comida.proteinas_totales_g || 0), carbohidratos: total.carbohidratos + Number(comida.carbohidratos_totales_g || 0), grasas: total.grasas + Number(comida.grasas_totales_g || 0) }), { calorias: 0, proteinas: 0, carbohidratos: 0, grasas: 0 }), [comidas]);
  const grupos = agruparPorDia(comidas); const fechaActual = new Date().toLocaleDateString("es-AR", { weekday: "long", day: "numeric", month: "long" });
  return <main className="app"><div className="content"><header><p>{fechaActual}</p><h1>Diario de comidas</h1></header><nav><button className={vista === "diario" ? "active" : ""} onClick={() => setVista("diario")}>Diario</button><button className={vista === "panel" ? "active" : ""} onClick={() => setVista("panel")}>Panel</button></nav>{vista === "diario" && <section className="summary"><div><span>Consumido hoy</span><strong>{Math.round(totalesHoy.calorias)} <small>/ 2000 kcal</small></strong></div><MacroBar etiqueta="Proteínas" valor={totalesHoy.proteinas} maximo={130} color="#c45a4a" /><MacroBar etiqueta="Carbohidratos" valor={totalesHoy.carbohidratos} maximo={250} color="#d4a14b" /><MacroBar etiqueta="Grasas" valor={totalesHoy.grasas} maximo={70} color="#7c9a7a" /></section>}{error && <p className="error">{error}</p>}{cargando ? <p className="empty-state">Cargando registros…</p> : vista === "panel" ? <AnalyticsPanel comidas={comidas} /> : grupos.length ? grupos.map(([dia, items]) => <section className="day" key={dia}><h2>{formatoDia(dia)}</h2>{items.map((comida) => <MealRow key={comida.id} comida={comida} abierta={expandido === comida.id} confirmando={confirmandoId === comida.id} onToggle={() => setExpandido(expandido === comida.id ? null : comida.id)} onConfirmar={() => setConfirmandoId(comida.id)} onCancelar={() => setConfirmandoId(null)} onBorrar={() => borrarComida(comida.id)} />)}</section>) : <p className="empty-state">Todavía no hay comidas registradas.<br />Usá el botón de abajo para cargar la primera.</p>}</div><NewMealDrawer abierto={panelAbierto} texto={textoJson} mensaje={mensaje} guardando={guardando} onTexto={setTextoJson} onCerrar={() => setPanelAbierto(false)} onGuardar={guardarRegistro} onAbrir={() => { setPanelAbierto(true); setMensaje(null); }} /></main>;
}
